//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 04:13:44 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/generateSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.gmit.sw.Model;
